'use client';

import { useState } from 'react';

interface FAQItem {
    question: string;
    answer: string;
}

export default function FAQ() {
    const [openIndex, setOpenIndex] = useState<number | null>(null);

    const faqs: FAQItem[] = [
        {
            question: "How does AI detection work?",
            answer: "Our AI detection system analyzes text patterns, sentence structures, and writing styles to identify content that may have been generated by AI tools. It compares your text against known AI writing patterns and provides a detailed breakdown of which sections appear AI-generated."
        },
        {
            question: "Can it detect a mix of human and AI writing?",
            answer: "Yes! Our advanced detection algorithm can identify mixed content, showing you exactly which parts are likely AI-generated and which parts appear to be human-written. This helps you understand where your text needs the most improvement."
        },
        {
            question: "Can this tool help improve my writing?",
            answer: "Absolutely! Monkify not only detects AI content but also helps you rewrite it to sound more natural and human. Our AI Humanizer feature preserves your meaning while making the text flow better and sound more authentic."
        },
        {
            question: "Does rewriting guarantee the text won't be detected?",
            answer: "While our humanizer significantly improves text naturalness and reduces AI detection scores, no tool can guarantee 100% undetectability. We recommend using it as a starting point and adding your own personal touch to make the content truly yours."
        },
        {
            question: "Will my text be stored or shared?",
            answer: "No. We take your privacy seriously. Your text is processed securely and is not stored on our servers or shared with third parties. Once you close your session, your content is permanently deleted."
        },
        {
            question: "Is this tool useful for students?",
            answer: "Yes! Monkify is designed specifically for students who want to ensure their writing sounds natural and authentic. It helps you learn to write better by showing you where your text might sound too robotic or AI-generated, allowing you to improve your writing skills."
        }
    ];

    const toggleFAQ = (index: number) => {
        setOpenIndex(openIndex === index ? null : index);
    };

    return (
        <div className="bg-white py-20">
            <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
                {/* Section Header */}
                <div className="text-center mb-12">
                    <h2 className="text-4xl md:text-5xl font-bold text-gray-900" style={{ fontFamily: 'var(--font-bungee)' }}>
                        Frequently asked questions
                    </h2>
                </div>

                {/* FAQ Items */}
                <div className="space-y-4">
                    {faqs.map((faq, index) => (
                        <div
                            key={index}
                            className="border border-gray-200 rounded-2xl overflow-hidden transition-all duration-300 hover:border-orange-300"
                        >
                            <button
                                onClick={() => toggleFAQ(index)}
                                className="w-full px-6 py-5 flex items-center justify-between text-left hover:bg-amber-50 transition-colors duration-200"
                            >
                                <span className="text-base font-semibold text-gray-900 pr-8" style={{ fontFamily: 'var(--font-fredoka)' }}>
                                    {faq.question}
                                </span>
                                <svg
                                    className={`w-5 h-5 text-gray-500 flex-shrink-0 transition-transform duration-300 ${openIndex === index ? 'rotate-180' : ''
                                        }`}
                                    fill="none"
                                    stroke="currentColor"
                                    viewBox="0 0 24 24"
                                >
                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
                                </svg>
                            </button>
                            <div
                                className={`overflow-hidden transition-all duration-300 ease-in-out ${openIndex === index ? 'max-h-96 opacity-100' : 'max-h-0 opacity-0'
                                    }`}
                            >
                                <div className="px-6 pb-5 pt-2">
                                    <p className="text-gray-600 leading-relaxed" style={{ fontFamily: 'var(--font-fredoka)' }}>
                                        {faq.answer}
                                    </p>
                                </div>
                            </div>
                        </div>
                    ))}
                </div>
            </div>
        </div>
    );
}
